# Generated by Django 6.0.3 on 2026-04-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_add_cohost_removed_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("event_invite", "Event Invite"),
                    ("event_cancelled", "Event Cancelled"),
                    ("join_request", "Join Request"),
                    ("cohost_added", "Co-host Added"),
                    ("cohost_invite", "Co-host Invite"),
                    ("cohost_invite_accepted", "Co-host Invite Accepted"),
                    ("cohost_invite_declined", "Co-host Invite Declined"),
                    ("cohost_removed", "Co-host Removed"),
                    ("magic_link_request", "Magic Link Request"),
                    ("waitlist_promoted", "Waitlist Promoted"),
                    ("event_flagged", "Event Flagged"),
                    ("text_blast_failures", "Text Blast Failures"),
                ],
                default="event_invite",
                max_length=32,
            ),
        ),
    ]
