include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    non_abstract_class_inherits_abstract_member: ignore

linter:
  rules:
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    use_colored_box: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 15
    maximum-nesting-level: 5
    number-of-parameters: 5
