targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/models/**
      json_serializable:
        generate_for:
          - lib/models/**
        options:
          field_rename: snake
          explicit_to_json: true
      riverpod_generator:
        generate_for:
          - lib/providers/**
