// Generated by `pnpm types:api` against http://localhost:8000/api/openapi.json.
// Run the Django backend (`make run`), then `pnpm --dir frontend types:api` to regenerate.
// This placeholder is committed so typecheck/build succeed before the first codegen run.

export type paths = Record<string, never>;
export type components = Record<string, never>;
export type operations = Record<string, never>;
