# Generated by Django 5.2.12 on 2026-03-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_event_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="partiful_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="rsvp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="whatsapp_link",
            field=models.URLField(blank=True),
        ),
    ]
