# Generated by Django 5.2.12 on 2026-03-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0006_eventrsvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="other_link",
            field=models.URLField(blank=True),
        ),
    ]
