# Generated by Django 5.2.12 on 2026-03-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0007_event_other_link"),
        ("community", "0007_joinrequest_phone_displayname"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityGuidelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Community Guidelines",
                "verbose_name_plural": "Community Guidelines",
            },
        ),
    ]
