# Generated by Django 5.2.12 on 2026-03-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0007_joinrequest_phone_displayname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinrequest",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
