# Generated by Django 5.2.12 on 2026-03-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0012_editablepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editablepage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
