# Generated by Django 5.2.12 on 2026-03-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0013_alter_editablepage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="donate_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
