# Generated by Django 5.2.12 on 2026-03-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0015_alter_event_end_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_url", models.URLField(blank=True, default="")),
                (
                    "bot_secret",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("group_id", models.CharField(blank=True, default="", max_length=256)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp Configuration",
                "verbose_name_plural": "WhatsApp Configuration",
            },
        ),
    ]
