# Generated by Django 5.2.12 on 2026-03-29 22:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0017_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinFormQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                (
                    "field_type",
                    models.CharField(
                        choices=[("text", "Text"), ("select", "Select")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="custom_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
