# Generated by Django 5.2.12 on 2026-03-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0021_survey_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[("official", "Official"), ("community", "Community")],
                default="community",
                max_length=20,
            ),
        ),
    ]
