# Generated by Django 5.2.12 on 2026-03-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0023_event_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("members_only", "Members only")],
                default="public",
                max_length=20,
            ),
        ),
    ]
