# Generated by Django 5.2.12 on 2026-03-31 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0024_event_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="invited_users",
            field=models.ManyToManyField(
                blank=True, related_name="invited_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
