# Generated by Django 5.2.12 on 2026-04-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0025_event_invited_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cashapp_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="venmo_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="zelle_info",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
