# Generated by Django 5.2.12 on 2026-04-02 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0030_eventpoll_polloption_eventpoll_winning_option_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="polloption",
            options={"ordering": ["datetime"]},
        ),
    ]
