# Generated by Django 6.0.3 on 2026-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0033_unique_constraints_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="invite_permission",
            field=models.CharField(
                choices=[("all_members", "All members"), ("co_hosts_only", "Co-hosts only")],
                default="all_members",
                max_length=20,
            ),
        ),
    ]
