# Generated by Django 6.0.3 on 2026-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0034_event_invite_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_plus_ones",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventrsvp",
            name="plus_one_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
