# Generated by Django 6.0.3 on 2026-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0035_event_allow_plus_ones_eventrsvp_plus_one_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventrsvp",
            name="plus_one_count",
        ),
        migrations.AddField(
            model_name="eventrsvp",
            name="has_plus_one",
            field=models.BooleanField(default=False),
        ),
    ]
