# Generated by Django 6.0.3 on 2026-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0039_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_attendees",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventrsvp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2026-01-01T00:00:00+00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventrsvp",
            name="status",
            field=models.CharField(
                choices=[
                    ("attending", "Attending"),
                    ("maybe", "Maybe"),
                    ("cant_go", "Can't go"),
                    ("waitlisted", "Waitlisted"),
                ],
                max_length=20,
            ),
        ),
    ]
