# Generated by Django 6.0.3 on 2026-04-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0043_event_status_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityguidelines",
            name="content_pm",
            field=models.TextField(default="", max_length=50000),
        ),
        migrations.AddField(
            model_name="document",
            name="content_pm",
            field=models.TextField(default="", max_length=50000),
        ),
        migrations.AddField(
            model_name="editablepage",
            name="content_pm",
            field=models.TextField(default="", max_length=50000),
        ),
        migrations.AddField(
            model_name="faq",
            name="content_pm",
            field=models.TextField(default="", max_length=50000),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content_pm",
            field=models.TextField(default="", max_length=50000),
        ),
        migrations.AddField(
            model_name="homepage",
            name="join_content_pm",
            field=models.TextField(default="", max_length=50000),
        ),
    ]
