# Generated by Django 6.0.3 on 2026-04-21 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0046_joinrequest_approved_at_joinrequest_approved_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="donate_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="join_content",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="join_content_html",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="join_content_pm",
        ),
    ]
