# Generated by Django 6.0.3 on 2026-04-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0047_remove_homepage_donate_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrsvp",
            name="attendance",
            field=models.CharField(
                choices=[("unknown", "Unknown"), ("attended", "Attended"), ("no_show", "No show")],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
