# Generated by Django 6.0.3 on 2026-04-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0048_eventrsvp_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelcomeMessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(default="", max_length=4000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Welcome Message Template",
                "verbose_name_plural": "Welcome Message Template",
            },
        ),
    ]
