# Generated by Django 6.0.3 on 2026-04-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0052_grandfather_cohost_invites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcohostinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("rescinded", "Rescinded"),
                    ("expired", "Expired"),
                    ("removed", "Removed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
