# Generated by Django 6.0.3 on 2026-04-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0053_add_cohost_invite_removed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="sms_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
