# Generated by Django 6.0.3 on 2026-05-16 04:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0054_joinrequest_sms_consent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.event",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="community.eventcomment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventCommentReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        choices=[
                            ("❤️", "Heart"),
                            ("😂", "Joy"),
                            ("🌱", "Seedling"),
                            ("🔥", "Fire"),
                            ("👍", "Thumbs up"),
                            ("😭", "Sob"),
                        ],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="community.eventcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="eventcomment",
            index=models.Index(
                fields=["event", "-created_at"], name="community_e_event_i_70d3b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcomment",
            index=models.Index(
                fields=["parent", "created_at"], name="community_e_parent__f280ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcommentreaction",
            index=models.Index(fields=["comment", "emoji"], name="community_e_comment_e65312_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventcommentreaction",
            constraint=models.UniqueConstraint(
                fields=("comment", "user", "emoji"), name="unique_comment_user_emoji_reaction"
            ),
        ),
    ]
