# Generated by Django 6.0.3 on 2026-05-16 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0055_eventcomment_eventcommentreaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcommentreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_comment_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
