# Generated by Django 5.2.12 on 2026-03-25 11:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("is_default", models.BooleanField(default=False)),
                ("permissions", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
