# Generated by Django 5.2.12 on 2026-03-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_needs_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
