# Generated by Django 5.2.12 on 2026-03-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_calendar_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, upload_to="profile_photos/"),
        ),
    ]
