# Generated by Django 5.2.12 on 2026-04-01 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_magiclogintoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="magiclogintoken",
            options={},
        ),
    ]
