# Generated by Django 5.2.12 on 2026-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_magiclogintoken_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
    ]
