# Generated by Django 6.0.3 on 2026-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_user_is_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_link_requested",
            field=models.BooleanField(default=False),
        ),
    ]
