# Generated by Django 6.0.3 on 2026-04-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_week_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
