# Generated by Django 6.0.3 on 2026-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_user_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_feed_scope",
            field=models.CharField(
                choices=[("all", "all events"), ("mine", "my events")], default="all", max_length=10
            ),
        ),
    ]
