# Generated by Django 6.0.3 on 2026-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_user_calendar_feed_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
